#####
#
# This file maps all the topics that are to be used on the uXRCE-DDS client.
#
#####
publications:

  - topic: /fmu/out/vehicle_attitude
    type: px4_msgs::msg::VehicleAttitude

  - topic: /fmu/out/vehicle_global_position
    type: px4_msgs::msg::VehicleGlobalPosition

  - topic: /fmu/out/vehicle_local_position
    type: px4_msgs::msg::VehicleLocalPosition

  - topic: /fmu/out/vehicle_odometry
    type: px4_msgs::msg::VehicleOdometry

  - topic: /fmu/out/vehicle_status
    type: px4_msgs::msg::VehicleStatus

  - topic: /fmu/out/mission_result
    type: px4_msgs::msg::MissionResult
  
  - topic: /fmu/out/vehicle_command
    type: px4_msgs::msg::VehicleCommand
  
  - topic: /fmu/out/vehicle_command_ack 
    type: px4_msgs::msg::VehicleCommandAck
  
  - topic: /fmu/out/airspeed_validated
    type: px4_msgs::msg::AirspeedValidated

  - topic: /fmu/out/airspeed_wind
    type: px4_msgs::msg::AirspeedWind

subscriptions:

  - topic: /fmu/in/vehicle_command
    type: px4_msgs::msg::VehicleCommand

  - topic: /fmu/in/trajectory_setpoint
    type: px4_msgs::msg::TrajectorySetpoint

  - topic: /fmu/in/config_control_setpoints
    type: px4_msgs::msg::VehicleControlMode

  - topic: /fmu/in/offboard_control_mode
    type: px4_msgs::msg::OffboardControlMode

subscriptions_multi: